#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_crud:
    path: /crud
    controller: App\Controller\CrudController::index
    
app_update:
    path: /crud/update/{slug}
    controller: App\Controller\CrudController::update
    
app_delete:
    path: /crud/delete/{slug}
    controller: App\Controller\CrudController::delete
